[2023-03-30T17:51:38.973+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: citi_bikes_nyc.unzip_data manual__2023-03-30T17:50:24.570961+00:00 [queued]>
[2023-03-30T17:51:38.980+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: citi_bikes_nyc.unzip_data manual__2023-03-30T17:50:24.570961+00:00 [queued]>
[2023-03-30T17:51:38.980+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-03-30T17:51:38.980+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 1
[2023-03-30T17:51:38.980+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-03-30T17:51:38.990+0000] {taskinstance.py:1304} INFO - Executing <Task(BashOperator): unzip_data> on 2023-03-30 17:50:24.570961+00:00
[2023-03-30T17:51:38.997+0000] {standard_task_runner.py:55} INFO - Started process 19153 to run task
[2023-03-30T17:51:38.999+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'citi_bikes_nyc', 'unzip_data', 'manual__2023-03-30T17:50:24.570961+00:00', '--job-id', '301', '--raw', '--subdir', 'DAGS_FOLDER/citi_bikes_nyc.py', '--cfg-path', '/tmp/tmpier3t5a4']
[2023-03-30T17:51:39.001+0000] {standard_task_runner.py:83} INFO - Job 301: Subtask unzip_data
[2023-03-30T17:51:39.042+0000] {task_command.py:389} INFO - Running <TaskInstance: citi_bikes_nyc.unzip_data manual__2023-03-30T17:50:24.570961+00:00 [running]> on host ea14cce7ead9
[2023-03-30T17:51:39.088+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=citi_bikes_nyc
AIRFLOW_CTX_TASK_ID=unzip_data
AIRFLOW_CTX_EXECUTION_DATE=2023-03-30T17:50:24.570961+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-30T17:50:24.570961+00:00
[2023-03-30T17:51:39.089+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-03-30T17:51:39.089+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', '\n            cd /opt/***/dags/data\n            unzip -o 202201-citibike-tripdata.csv.zip\n        ']
[2023-03-30T17:51:39.101+0000] {subprocess.py:86} INFO - Output:
[2023-03-30T17:51:39.102+0000] {subprocess.py:93} INFO - /bin/bash: line 3: unzip: command not found
[2023-03-30T17:51:39.103+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2023-03-30T17:51:39.110+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2023-03-30T17:51:39.113+0000] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=citi_bikes_nyc, task_id=unzip_data, execution_date=20230330T175024, start_date=20230330T175138, end_date=20230330T175139
[2023-03-30T17:51:39.122+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 301 for task unzip_data (Bash command failed. The command returned a non-zero exit code 127.; 19153)
[2023-03-30T17:51:39.131+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-03-30T17:51:39.151+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
