[2023-03-30T14:19:47.114+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: citi_bikes_nyc.download_citi_bike_data manual__2023-03-30T14:17:15.264464+00:00 [queued]>
[2023-03-30T14:19:47.121+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: citi_bikes_nyc.download_citi_bike_data manual__2023-03-30T14:17:15.264464+00:00 [queued]>
[2023-03-30T14:19:47.121+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-03-30T14:19:47.121+0000] {taskinstance.py:1284} INFO - Starting attempt 2 of 3
[2023-03-30T14:19:47.121+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-03-30T14:19:47.132+0000] {taskinstance.py:1304} INFO - Executing <Task(BashOperator): download_citi_bike_data> on 2023-03-30 14:17:15.264464+00:00
[2023-03-30T14:19:47.138+0000] {standard_task_runner.py:55} INFO - Started process 761 to run task
[2023-03-30T14:19:47.140+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'citi_bikes_nyc', 'download_citi_bike_data', 'manual__2023-03-30T14:17:15.264464+00:00', '--job-id', '227', '--raw', '--subdir', 'DAGS_FOLDER/citi_bikes_nyc.py', '--cfg-path', '/tmp/tmpgop_v7yc']
[2023-03-30T14:19:47.140+0000] {standard_task_runner.py:83} INFO - Job 227: Subtask download_citi_bike_data
[2023-03-30T14:19:47.183+0000] {task_command.py:389} INFO - Running <TaskInstance: citi_bikes_nyc.download_citi_bike_data manual__2023-03-30T14:17:15.264464+00:00 [running]> on host ea14cce7ead9
[2023-03-30T14:19:47.234+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=citi_bikes_nyc
AIRFLOW_CTX_TASK_ID=download_citi_bike_data
AIRFLOW_CTX_EXECUTION_DATE=2023-03-30T14:17:15.264464+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-30T14:17:15.264464+00:00
[2023-03-30T14:19:47.235+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-03-30T14:19:47.235+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'curl -o dags/data/202201-citibike-tripdata.csv.zip https://s3.amazonaws.com/tripdata/202201-citibike-tripdata.csv.zip']
[2023-03-30T14:19:47.245+0000] {subprocess.py:86} INFO - Output:
[2023-03-30T14:19:47.250+0000] {subprocess.py:93} INFO -   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
[2023-03-30T14:19:47.250+0000] {subprocess.py:93} INFO -                                  Dload  Upload   Total   Spent    Left  Speed
[2023-03-30T14:19:47.936+0000] {subprocess.py:93} INFO -   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0  0 33.9M    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0Warning: Failed to create the file dags/data/202201-citibike-tripdata.csv.zip:
[2023-03-30T14:19:47.936+0000] {subprocess.py:93} INFO - Warning: No such file or directory
[2023-03-30T14:19:47.936+0000] {subprocess.py:93} INFO -   0 33.9M    0  1568    0     0   2289      0  4:19:11 --:--:--  4:19:11  2285
[2023-03-30T14:19:47.936+0000] {subprocess.py:93} INFO - curl: (23) Failure writing output to destination
[2023-03-30T14:19:47.937+0000] {subprocess.py:97} INFO - Command exited with return code 23
[2023-03-30T14:19:47.946+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 23.
[2023-03-30T14:19:47.949+0000] {taskinstance.py:1327} INFO - Marking task as UP_FOR_RETRY. dag_id=citi_bikes_nyc, task_id=download_citi_bike_data, execution_date=20230330T141715, start_date=20230330T141947, end_date=20230330T141947
[2023-03-30T14:19:47.959+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 227 for task download_citi_bike_data (Bash command failed. The command returned a non-zero exit code 23.; 761)
[2023-03-30T14:19:47.994+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-03-30T14:19:48.010+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
