[2023-03-30T17:10:52.827+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: citi_bikes_nyc.download_citi_bike_data manual__2023-03-30T17:10:51.770950+00:00 [queued]>
[2023-03-30T17:10:52.834+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: citi_bikes_nyc.download_citi_bike_data manual__2023-03-30T17:10:51.770950+00:00 [queued]>
[2023-03-30T17:10:52.834+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-03-30T17:10:52.834+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 2
[2023-03-30T17:10:52.834+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-03-30T17:10:52.848+0000] {taskinstance.py:1304} INFO - Executing <Task(BashOperator): download_citi_bike_data> on 2023-03-30 17:10:51.770950+00:00
[2023-03-30T17:10:52.854+0000] {standard_task_runner.py:55} INFO - Started process 14790 to run task
[2023-03-30T17:10:52.857+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'citi_bikes_nyc', 'download_citi_bike_data', 'manual__2023-03-30T17:10:51.770950+00:00', '--job-id', '278', '--raw', '--subdir', 'DAGS_FOLDER/citi_bikes_nyc.py', '--cfg-path', '/tmp/tmpormreq09']
[2023-03-30T17:10:52.858+0000] {standard_task_runner.py:83} INFO - Job 278: Subtask download_citi_bike_data
[2023-03-30T17:10:52.905+0000] {task_command.py:389} INFO - Running <TaskInstance: citi_bikes_nyc.download_citi_bike_data manual__2023-03-30T17:10:51.770950+00:00 [running]> on host ea14cce7ead9
[2023-03-30T17:10:53.038+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=citi_bikes_nyc
AIRFLOW_CTX_TASK_ID=download_citi_bike_data
AIRFLOW_CTX_EXECUTION_DATE=2023-03-30T17:10:51.770950+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-30T17:10:51.770950+00:00
[2023-03-30T17:10:53.039+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-03-30T17:10:53.039+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'curl -o /opt/***/dags/data/202201-citibike-tripdata.csv.zip https://s3.amazonaws.com/tripdata/202201-citibike-tripdata.csv.zip']
[2023-03-30T17:10:53.052+0000] {subprocess.py:86} INFO - Output:
[2023-03-30T17:10:53.059+0000] {subprocess.py:93} INFO -   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
[2023-03-30T17:10:53.059+0000] {subprocess.py:93} INFO -                                  Dload  Upload   Total   Spent    Left  Speed
[2023-03-30T17:11:08.085+0000] {local_task_job.py:224} WARNING - State of this instance has been externally set to up_for_retry. Terminating instance.
[2023-03-30T17:11:08.086+0000] {process_utils.py:133} INFO - Sending Signals.SIGTERM to group 14790. PIDs of all processes in the group: [14791, 14790]
[2023-03-30T17:11:08.086+0000] {process_utils.py:84} INFO - Sending the signal Signals.SIGTERM to group 14790
[2023-03-30T17:11:08.086+0000] {taskinstance.py:1483} ERROR - Received SIGTERM. Terminating subprocesses.
[2023-03-30T17:11:08.087+0000] {subprocess.py:104} INFO - Sending SIGTERM signal to process group
[2023-03-30T17:11:08.095+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 191, in execute
    cwd=self.cwd,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/subprocess.py", line 91, in run_command
    for raw_line in iter(self.sub_process.stdout.readline, b""):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1485, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2023-03-30T17:11:08.099+0000] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=citi_bikes_nyc, task_id=download_citi_bike_data, execution_date=20230330T171051, start_date=20230330T171052, end_date=20230330T171108
[2023-03-30T17:11:08.110+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 278 for task download_citi_bike_data (Task received SIGTERM signal; 14790)
[2023-03-30T17:11:08.139+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=14791, status='terminated', started='17:10:52') (14791) terminated with exit code None
[2023-03-30T17:11:08.139+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=14790, status='terminated', exitcode=1, started='17:10:52') (14790) terminated with exit code 1
