[2023-03-30T17:16:18.037+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: citi_bikes_nyc.unzip_data manual__2023-03-30T17:11:34.964263+00:00 [queued]>
[2023-03-30T17:16:18.044+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: citi_bikes_nyc.unzip_data manual__2023-03-30T17:11:34.964263+00:00 [queued]>
[2023-03-30T17:16:18.044+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-03-30T17:16:18.044+0000] {taskinstance.py:1284} INFO - Starting attempt 2 of 2
[2023-03-30T17:16:18.044+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-03-30T17:16:18.054+0000] {taskinstance.py:1304} INFO - Executing <Task(BashOperator): unzip_data> on 2023-03-30 17:11:34.964263+00:00
[2023-03-30T17:16:18.061+0000] {standard_task_runner.py:55} INFO - Started process 15379 to run task
[2023-03-30T17:16:18.064+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'citi_bikes_nyc', 'unzip_data', 'manual__2023-03-30T17:11:34.964263+00:00', '--job-id', '285', '--raw', '--subdir', 'DAGS_FOLDER/citi_bikes_nyc.py', '--cfg-path', '/tmp/tmpigfj13b6']
[2023-03-30T17:16:18.066+0000] {standard_task_runner.py:83} INFO - Job 285: Subtask unzip_data
[2023-03-30T17:16:18.110+0000] {task_command.py:389} INFO - Running <TaskInstance: citi_bikes_nyc.unzip_data manual__2023-03-30T17:11:34.964263+00:00 [running]> on host ea14cce7ead9
[2023-03-30T17:16:18.163+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=citi_bikes_nyc
AIRFLOW_CTX_TASK_ID=unzip_data
AIRFLOW_CTX_EXECUTION_DATE=2023-03-30T17:11:34.964263+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-30T17:11:34.964263+00:00
[2023-03-30T17:16:18.165+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-03-30T17:16:18.165+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', ['cd /opt/***/dags/data', 'unzip -o 202201-citibike-tripdata.csv.zip']]
[2023-03-30T17:16:18.166+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 191, in execute
    cwd=self.cwd,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/subprocess.py", line 83, in run_command
    preexec_fn=pre_exec,
  File "/usr/local/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/usr/local/lib/python3.7/subprocess.py", line 1482, in _execute_child
    restore_signals, start_new_session, preexec_fn)
TypeError: expected str, bytes or os.PathLike object, not list
[2023-03-30T17:16:18.172+0000] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=citi_bikes_nyc, task_id=unzip_data, execution_date=20230330T171134, start_date=20230330T171618, end_date=20230330T171618
[2023-03-30T17:16:18.180+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 285 for task unzip_data (expected str, bytes or os.PathLike object, not list; 15379)
[2023-03-30T17:16:18.195+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-03-30T17:16:18.216+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
