[2023-03-30T17:17:50.858+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: citi_bikes_nyc.unzip_data manual__2023-03-30T17:11:34.964263+00:00 [queued]>
[2023-03-30T17:17:50.867+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: citi_bikes_nyc.unzip_data manual__2023-03-30T17:11:34.964263+00:00 [queued]>
[2023-03-30T17:17:50.867+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-03-30T17:17:50.867+0000] {taskinstance.py:1284} INFO - Starting attempt 6 of 6
[2023-03-30T17:17:50.867+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-03-30T17:17:50.880+0000] {taskinstance.py:1304} INFO - Executing <Task(BashOperator): unzip_data> on 2023-03-30 17:11:34.964263+00:00
[2023-03-30T17:17:50.886+0000] {standard_task_runner.py:55} INFO - Started process 15541 to run task
[2023-03-30T17:17:50.889+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'citi_bikes_nyc', 'unzip_data', 'manual__2023-03-30T17:11:34.964263+00:00', '--job-id', '290', '--raw', '--subdir', 'DAGS_FOLDER/citi_bikes_nyc.py', '--cfg-path', '/tmp/tmp5aexu_o6']
[2023-03-30T17:17:50.891+0000] {standard_task_runner.py:83} INFO - Job 290: Subtask unzip_data
[2023-03-30T17:17:50.940+0000] {task_command.py:389} INFO - Running <TaskInstance: citi_bikes_nyc.unzip_data manual__2023-03-30T17:11:34.964263+00:00 [running]> on host ea14cce7ead9
[2023-03-30T17:17:51.110+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=citi_bikes_nyc
AIRFLOW_CTX_TASK_ID=unzip_data
AIRFLOW_CTX_EXECUTION_DATE=2023-03-30T17:11:34.964263+00:00
AIRFLOW_CTX_TRY_NUMBER=6
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-30T17:11:34.964263+00:00
[2023-03-30T17:17:51.111+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-03-30T17:17:51.112+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', ['unzip -o /opt/***/dags/data/202201-citibike-tripdata.csv.zip']]
[2023-03-30T17:17:51.113+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 191, in execute
    cwd=self.cwd,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/subprocess.py", line 83, in run_command
    preexec_fn=pre_exec,
  File "/usr/local/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/usr/local/lib/python3.7/subprocess.py", line 1482, in _execute_child
    restore_signals, start_new_session, preexec_fn)
TypeError: expected str, bytes or os.PathLike object, not list
[2023-03-30T17:17:51.120+0000] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=citi_bikes_nyc, task_id=unzip_data, execution_date=20230330T171134, start_date=20230330T171750, end_date=20230330T171751
[2023-03-30T17:17:51.132+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 290 for task unzip_data (expected str, bytes or os.PathLike object, not list; 15541)
[2023-03-30T17:17:51.141+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-03-30T17:17:51.166+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
