[2023-03-30T17:17:37.166+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: citi_bikes_nyc.unzip_data scheduled__2023-03-29T17:11:29.642271+00:00 [queued]>
[2023-03-30T17:17:37.173+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: citi_bikes_nyc.unzip_data scheduled__2023-03-29T17:11:29.642271+00:00 [queued]>
[2023-03-30T17:17:37.173+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-03-30T17:17:37.173+0000] {taskinstance.py:1284} INFO - Starting attempt 2 of 2
[2023-03-30T17:17:37.173+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-03-30T17:17:37.184+0000] {taskinstance.py:1304} INFO - Executing <Task(BashOperator): unzip_data> on 2023-03-29 17:11:29.642271+00:00
[2023-03-30T17:17:37.190+0000] {standard_task_runner.py:55} INFO - Started process 15509 to run task
[2023-03-30T17:17:37.193+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'citi_bikes_nyc', 'unzip_data', 'scheduled__2023-03-29T17:11:29.642271+00:00', '--job-id', '289', '--raw', '--subdir', 'DAGS_FOLDER/citi_bikes_nyc.py', '--cfg-path', '/tmp/tmpfuwkfi9l']
[2023-03-30T17:17:37.194+0000] {standard_task_runner.py:83} INFO - Job 289: Subtask unzip_data
[2023-03-30T17:17:37.238+0000] {task_command.py:389} INFO - Running <TaskInstance: citi_bikes_nyc.unzip_data scheduled__2023-03-29T17:11:29.642271+00:00 [running]> on host ea14cce7ead9
[2023-03-30T17:17:37.286+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=citi_bikes_nyc
AIRFLOW_CTX_TASK_ID=unzip_data
AIRFLOW_CTX_EXECUTION_DATE=2023-03-29T17:11:29.642271+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-03-29T17:11:29.642271+00:00
[2023-03-30T17:17:37.287+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-03-30T17:17:37.288+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', ['unzip -o /opt/***/dags/data/202201-citibike-tripdata.csv.zip']]
[2023-03-30T17:17:37.288+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 191, in execute
    cwd=self.cwd,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/subprocess.py", line 83, in run_command
    preexec_fn=pre_exec,
  File "/usr/local/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/usr/local/lib/python3.7/subprocess.py", line 1482, in _execute_child
    restore_signals, start_new_session, preexec_fn)
TypeError: expected str, bytes or os.PathLike object, not list
[2023-03-30T17:17:37.294+0000] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=citi_bikes_nyc, task_id=unzip_data, execution_date=20230329T171129, start_date=20230330T171737, end_date=20230330T171737
[2023-03-30T17:17:37.302+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 289 for task unzip_data (expected str, bytes or os.PathLike object, not list; 15509)
[2023-03-30T17:17:37.324+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-03-30T17:17:37.342+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
